#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if git diff --cached --quiet -- "./"
then
  echo "No FE changes, skipping FE Git Hooks"
  exit 0
else
  echo "FE Changes detected, running FE Git Hooks"
  cd ./ || exit
  pnpm typecheck && pnpm lint-staged
fi
